name: "Check Pull Request"

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixPath:
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-25.05.tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: "nixpkgs=${{ matrix.nixPath }}"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix (Read-Only)
        uses: cachix/cachix-action@v16
        with:
          name: francynox

      - name: Build & Check all packages
        run: |
          nix flake check --show-trace --override-input nixpkgs ${{ matrix.nixPath }}
